### ISSUE TITLE
2016-06-10 ~ GitHub API Users Events R4

### ISSUE THREAD

**Issue by theo-armour** [jaanga/jaanga.github.io#11]
![image](https://cloud.githubusercontent.com/assets/547626/15981300/44210bbe-2f28-11e6-9419-4efbbc01c525.png)

@paulmasson 

Nice big update!

Future updates will come from Jaanga.github.io rather then theo-armour.github.io as the primary dev effort is in jaanga and theo-armour is just a user site.

## Change log

* Add much to read me file
* Add more user data
* Add many more event type handles
* Calling functions using bracket names
	* Simplifies branching a lot
* Code clean-up and bug fixes. Thanks Paul!

**Comment by paulmasson** [comment]
@theo-armour my organization list doesn't include jaanga. The list for @hunvreus has a 'null' entry.

And now that you're sliding the entire content, scooch the hamburger back down please!

Otherwise very cool!

**Comment by theo-armour** [comment]
@paulmasson 

> my organization list doesn't include jaanga.

You are list as a private member:

https://github.com/orgs/jaanga/people

> The list for @hunvreus has a 'null' entry.

Some descriptions that are null show nothing and other show 'null'. A bit weird. Looking into this.

> And now that you're sliding the entire content, scooch the hamburger back down please!

I'm thinking about centering the whole thing. Se we'll see what happens then.

Thanks for the observations.

***

Got any wish list items?

**Comment by paulmasson** [comment]
How about local time for events? Looks like the default is UTC+0.

**Comment by paulmasson** [comment]
@theo-armour when is this moving to jaanga.github.io? I want to link to the most current version from my Github landing page.

**Comment by paulmasson** [comment]
@theo-armour one more bug: when loading the page with an existing hash, the menu should reflect that.

**Comment by theo-armour** [comment]
@paulmasson 

> when loading the page with an existing hash, the menu should reflect that.

Dropdown list selected name now stays selected when pages are changed.


> when is this moving to jaanga.github.io?

It's been here the whole time


> How about local time for events? Looks like the default is UTC+0.

If GitHub says use UTC+0 then who are we to say something different?
