### ISSUE TITLE
2016-06-13 ~ GitHub API Users Event R5

### ISSUE THREAD

**Issue by theo-armour** [jaanga/jaanga.github.io#13]
![image](https://cloud.githubusercontent.com/assets/547626/16001861/6e3fea4a-3109-11e6-8099-4e220d1cc11b.png)

@paulmasson 

### 2016-06-13 R5

* Add Gists
* Update the selUser.selectedIndex with any onHashChange event
* Centered the content in window

**Comment by paulmasson** [comment]
@theo-armour another idea: linking to an entire repository for commit evente in not so interesting. Have the name of the repository there but link to either the commit or the full document that was altered.

**Comment by theo-armour** [comment]
@paulmasson 

> link to either the commit or the full document that was altered.

Great suggestion. Thank you.

It's been committed. See:

[GitHub API User Events R6]( https://jaanga.github.io/cookbook-html/examples/github-api-rss/github-api-users-events/ )

**Comment by paulmasson** [comment]
@theo-armour just noticed in reviewing my work of the last two hours that a push event with more than one commit only links to the first one. Any way around that?

**Comment by theo-armour** [comment]
@paulmasson 

In GitHub desktop, go to 'Open in git Shell'

$ git add -vA .
$ git commit -am "message here"
$ git push

seems to commit everything

**Comment by paulmasson** [comment]
@theo-armour since this came from one of your issues on Jaanga, I thought that would be enough context. I mean your API viewer only links to the first commit, not a list of all of them.

**Comment by theo-armour** [comment]
> since this came from one of your issues on Jaanga, I thought that would be enough context.

Kindly remember that GitHb issues arrive via email. Since there's little visible context. It's very easy to mis-judge the context. Here's what I saw:

![image](https://cloud.githubusercontent.com/assets/547626/16549549/1fff079c-4155-11e6-9d12-8c08e39c27d2.png)

The lesson I am learning on online support is to be specific as possible in the body of the message
***

> I mean your API viewer only links to the first commit, not a list of all of them.

Could you identify a sample event from here:

https://jaanga.github.io/cookbook-html/examples/github-api-rss/github-api-users-events/github-api-users-events-r6.html#PaulMasson

Just path and # will do

**Comment by paulmasson** [comment]
@theo-armour how about this one:

```
PushEvent
5. 01:56:46
Repository: paulmasson/three.js
Message: Add iOS workaround to MeshBasicMaterial - Size: 6 - Length: 6
```

**Comment by theo-armour** [comment]
@paulmasson 

Can you supply a more appropriate URL for the link in the message?

**Comment by paulmasson** [comment]
@theo-armour URL currently points to single commit of six total:

https://github.com/paulmasson/three.js/commit/29cac1e0c536450069df979b6f620d90cf7c69f4

How about a drop-down list of commits when more than one with an appropriate title?

No rush on this. Since I've come to rely on this viewer, it's a feature I'd like to see.

**Comment by theo-armour** [comment]
Paul

> URL currently points to single commit of six total:

I know this. I can click too, you know.

I am just looking for a sample of where it *should* link to...


> Since I've come to rely on this viewer, it's a feature I'd like to see.

Me too. And working on aspects of User right now

**Comment by theo-armour** [comment]
BTW, here is the current work on events

https://jaanga.github.io/cookbook-html/examples/github-api-rss/github-api-events/github-api-events-r2.html

You will notice that 'actor' is identified. Also more events are covered - and in a simpler manner.

The issue you bring up is a WIP.
