### ISSUE TITLE
2016-06-26 ~ GitHub API Events

### ISSUE THREAD

**Issue by theo-armour** [jaanga/jaanga.github.io#17]
![image](https://cloud.githubusercontent.com/assets/547626/16370238/d1583ff8-3bf2-11e6-85c2-d4cef82dede1.png)

@paulmasson 

Anything wrong or missing?

Any suggestions for organizations to add?

### Mission

* To provide a fast and effective way to visualize the just events of a number of GitHub orgs or users with many followers
* To be combined with other modules to show many aspects of an organization's profile

### 2016-06-26 ~ R2

* Add actor's login and link to many events
* Most events have mostly reasonable data appearing

**Comment by paulmasson** [comment]
MrDoob isn't an organization per se. And who wants to follow Facebook? Or Google? Ew...

**Comment by theo-armour** [comment]
@paulmasson 

Agreed on Mr.doob not being 'organized' though wish he were.

Can you think of fun peeps to replace the 'ew'ies?

Will next be working on happenings in repos and organization activity in general.

Then will push all of that and more into updating the individual user script

The mission is to reduce the amount of readme and docs stuff that scripts need because so much background material such as commit messages and issues is readily available.

**Comment by theo-armour** [comment]
![image](https://cloud.githubusercontent.com/assets/547626/16552816/ea771050-4178-11e6-8106-cdb90fa3846c.png)

@paulmasson 

[GitHub API Events R2.1]( https://jaanga.github.io/cookbook-html/examples/github-api-rss/github-api-events/ ) may address the issues you raised in #13 

Changes here will eventually be added to the main event.
