### ISSUE TITLE
Badly broken page

### ISSUE THREAD

**Issue by paulmasson** [jaanga/jaanga.github.io#36]
This page doesn't display anything at all: http://jaanga.github.io/algebraic-surfaces/

Needs updating!

**Comment by theo-armour** [comment]
@paulmasson 

Good catch!

I wonder when I will ever get around to fixing this stuff. The ongoing issue is that I have never found anybody else who wants to play with this stuff. And as you are finding out with Sage, working with others adds all sorts of dimensions - including range - that make such efforts more attractive than working is in solitude.

The fun thing is that I look at all this code and think immediately of ways of drastically simplifying things and making code easier to read. So it goes.

Theo

**Comment by theo-armour** [comment]
BTW, this page - add quite a bit later - still works:

http://jaanga.github.io/algesurf/

**Comment by paulmasson** [comment]
@theo-armour set Three.js version to r64 and now works. If that satisfies you then close this issue.

You might considering setting all of your old pages to time-appropriate versions as I just did for this one. No point in having an online legacy if stuff just doesn't work...

**Comment by theo-armour** [comment]
> No point in having an online legacy if stuff just doesn't work...

Bingo!
